name: aiot_nano
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_native_splash: ^2.3.4
  flutter:
    sdk: flutter
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  firebase_database: ^10.0.9
  firebase_storage: ^11.0.10
  lottie: ^2.7.0
  url_launcher: ^6.1.14
  cloud_firestore: ^4.17.5
  convex_bottom_bar: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  sleek_circular_slider: ^2.0.1
  intl: ^0.18.1
  geocoding: ^2.2.2
  geolocator_web: ^2.2.0
  geolocator: ^10.1.0
  http: ^1.1.0
  camera: ^0.10.5+5
  image: ^4.0.17
  path: ^1.8.3
  path_provider: ^2.1.5
  image_picker: ^0.8.8
  tflite_flutter: ^0.10.3
  flutter_svg_provider: ^1.0.7
  share_plus: ^7.2.1
  webview_flutter: ^4.4.1
  shimmer: ^3.0.0
  syncfusion_flutter_gauges: ^23.1.42
  audioplayers: ^6.1.0
  dio: ^5.7.0
  tflite_audio: ^0.3.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"

dev_dependencies:
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SquadaOne
      fonts:
        - asset: assets/fonts/SquadaOne-Regular.ttf
    - family: ContrailOne
      fonts:
        - asset: assets/fonts/ContrailOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

  assets:
    - assets/
    - assets/images/
    - assets/locales/
    - assets/models/
    - assets/models/CayOi/
    - assets/models/CaChua/
    - assets/icons/
    - assets/weather/
    - assets/fonts/
    - assets/json/model/model_tanaman.json

flutter_native_splash:
  color: "#e1f5fe"
  image: assets/images/bgr.jpg
  color_dark: "#042a49"
  image_dark: assets/images/app_logo.png
  android_12:
    image: assets/images/app_logo.png
    color: "#42a5f5"
    icon_background_color: "#eeeeee"
  fullscreen: true
