// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9uR_TPOtfgdY61FK2dkm6vi7NIlFF36k',
    appId: '1:805272252636:web:919db8094677c532ebc419',
    messagingSenderId: '805272252636',
    projectId: 'farm-care-ai',
    authDomain: 'farm-care-ai.firebaseapp.com',
    storageBucket: 'farm-care-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVTDhcA_POUoK_kRv9HivxkW6_7rkx7bw',
    appId: '1:805272252636:android:ec48fa82a3a89c39ebc419',
    messagingSenderId: '805272252636',
    projectId: 'farm-care-ai',
    storageBucket: 'farm-care-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsg7_uTzVjEKDdEaFy8ilbW70ZTJy34EM',
    appId: '1:805272252636:ios:f82e03fd3e023241ebc419',
    messagingSenderId: '805272252636',
    projectId: 'farm-care-ai',
    storageBucket: 'farm-care-ai.appspot.com',
    iosClientId: '805272252636-3mpui7f9ft79k70rphi0q4gbeopgcm9p.apps.googleusercontent.com',
    iosBundleId: 'com.khoahockythuat.farmCareAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsg7_uTzVjEKDdEaFy8ilbW70ZTJy34EM',
    appId: '1:805272252636:ios:45421d9c6fe88e4aebc419',
    messagingSenderId: '805272252636',
    projectId: 'farm-care-ai',
    storageBucket: 'farm-care-ai.appspot.com',
    iosClientId: '805272252636-6vvqaci42rtjbu7mhr7rmr80er8u2ht0.apps.googleusercontent.com',
    iosBundleId: 'com.khoahockythuat.farmCareAi.RunnerTests',
  );
}
