# .github/workflows/android_Build_Auto.yml
name: MyApp Release android_Build_Auto

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
jobs:
  minhduc3009_job_build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
    
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: "12.x"
            cache: 'gradle'
    
        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            flutter-version: "3.13.0"
            channel: 'stable'
            cache: true
    
        - name: Install dependencies
          run: flutter pub get
    
#         - name: Analyze
#           run: flutter analyze
    
        # - name: Test
        #   run: flutter test
    
        - name: Build APK
          run: flutter build apk
    
        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: app-release.apk
            path: build/app/outputs/flutter-apk/app-release.apk